"""add telegram links table and unique phone

Revision ID: 6bfc2d2125aa
Revises: 0b8dab1bde96
Create Date: 2026-08-25 02:19:09.588536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfc2d2125aa'
down_revision: Union[str, Sequence[str], None] = '0b8dab1bde96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_links',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_unique_constraint('uq_users_phone', 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_phone', 'users', type_='unique')
    op.drop_table('telegram_links')
    # ### end Alembic commands ###
