"""add name to branches

Revision ID: 8fe7e384bfd1
Revises: 58a200fe7c0b
Create Date: 2026-08-25 16:52:11.750110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe7e384bfd1'
down_revision: Union[str, Sequence[str], None] = '58a200fe7c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'name')
    # ### end Alembic commands ###
